[project]
name = "django-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.1",
    "django-allauth>=65.8.1",
    "django-cleanup>=9.0.0",
    "django-htmx>=1.23.0",
    "pillow>=11.2.1",
]
